# Generated by Django 3.2.16 on 2023-04-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230405_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
