# Generated by Django 3.2.16 on 2023-04-07 22:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='image', max_length=150)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
