# Generated by Django 3.2.16 on 2023-04-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
